# Generated by Django 5.2.11 on 2026-02-06 04:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('dress_code', models.CharField(max_length=200)),
                ('last_seen_location', models.CharField(max_length=200)),
                ('is_outsider', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to='missing_persons/')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='Pending Investigation', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
