# Generated by Django 5.2.11 on 2026-02-12 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cctvvideo_student_adminuser_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='cctvvideo',
            name='missing_person',
            field=models.ForeignKey(blank=True, help_text='Select missing person to detect', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.missingperson'),
        ),
    ]
