# Generated by Django 4.2.7 on 2026-02-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cctvvideo_missing_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='is_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detection',
            name='confidence_score',
            field=models.FloatField(default=0),
        ),
    ]
