# Generated by Django 5.2.11 on 2026-02-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_detection_is_match_alter_detection_confidence_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
    ]
