# Generated by Django 4.2.7 on 2026-03-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_name_student_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='face_crop',
            field=models.ImageField(blank=True, null=True, upload_to='detected_faces/'),
        ),
    ]
