# Generated by Django 4.2.7 on 2026-03-09 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_detection_face_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='matched_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missing_reports', to='api.student'),
        ),
    ]
