# Generated by Django 6.0.3 on 2026-03-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_missingperson_matched_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='student_id',
            field=models.CharField(blank=True, default='', help_text='Student/Admission ID — must match a student_database folder name', max_length=50),
        ),
    ]
