# Generated by Django 6.0.3 on 2026-03-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_missingperson_student_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missingperson',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='missingperson',
            name='found_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='found_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='found_location_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='last_seen_location_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='missing_persons/'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('Pending Investigation', 'Pending Investigation'), ('Processing', 'Processing'), ('Detected', 'Detected'), ('Completed', 'Completed')], default='Pending Investigation', max_length=50),
        ),
    ]
